name: Run Pipeline Immediately

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      authorization_url: ${{ secrets.AUTHORIZATION_URL }}
      inoreader_client_id: ${{ secrets.INOREADER_CLIENT_ID }}
      inoreader_key:       ${{ secrets.INOREADER_KEY }}
      oauth_client_id:     ${{ secrets.OAUTH_CLIENT_ID }}
      od_authority:        ${{ secrets.OD_AUTHORITY }}
      od_client_id:        ${{ secrets.OD_CLIENT_ID }}
      od_client_secret:    ${{ secrets.OD_CLIENT_SECRET }}
      od_drive_id:         ${{ secrets.OD_DRIVE_ID }}
      od_parent_item:      ${{ secrets.OD_PARENT_ITEM }}
      od_resource:         ${{ secrets.OD_RESOURCE }}
      od_scopes:           ${{ secrets.OD_SCOPES }}
      od_tenant_id:        ${{ secrets.OD_TENANT_ID }}
      openai_apikey:       ${{ secrets.OPENAI_APIKEY }}
      username:            ${{ secrets.USERNAME }}
      password:            ${{ secrets.PASSWORD }}
      token_url:           ${{ secrets.TOKEN_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python main.py
