name: Run Pipeline Immediately

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      AUTHORIZATION_URL: ${{ secrets.AUTHORIZATION_URL }}
      INOREADER_CLIENT_ID: ${{ secrets.INOREADER_CLIENT_ID }}
      INOREADER_KEY:       ${{ secrets.INOREADER_KEY }}
      OAUTH_CLIENT_ID:     ${{ secrets.OAUTH_CLIENT_ID }}
      OD_AUTHORITY:        ${{ secrets.OD_AUTHORITY }}
      OD_CLIENT_ID:        ${{ secrets.OD_CLIENT_ID }}
      OD_CLIENT_SECRET:    ${{ secrets.OD_CLIENT_SECRET }}
      OD_CLIENT_VALUE:     ${{ secrets.OD_CLIENT_VALUE }}
      OD_DRIVE_ID:         ${{ secrets.OD_DRIVE_ID }}
      OD_PARENT_ITEM:      ${{ secrets.OD_PARENT_ITEM }}
      OD_RESOURCE:         ${{ secrets.OD_RESOURCE }}
      OD_SCOPES:           ${{ secrets.OD_SCOPES }}
      OD_TENANT_ID:        ${{ secrets.OD_TENANT_ID }}
      OPENAI_APIKEY:       ${{ secrets.OPENAI_APIKEY }}
      USERNAME:            ${{ secrets.USERNAME }}
      PASSWORD:            ${{ secrets.PASSWORD }}
      TOKEN_URL:           ${{ secrets.TOKEN_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python main.py
